Ejercicio 11: Señala la respuesta correcta sobre las excepciones:

a. Una sentencia try no puede estar dentro de un bloque de otra secuencia try b.	==> Falso, se pueden anidad mas de un try-catch

b. Un bloque try va seguido por un único bloque catch								==> Falso, podria tener mas de un bloque catch

c. Cada bloque catch especifica el tipo de excepción que puede atrapar y contiene
un manejador de excepciones.														==> Verdadero

d. El bloque finally se ejecuta si no ocurre la excepción.							==> Falso, el bloque se ejecuta siempre